services:
  cache:
    image: redis:7-alpine@sha256:02419de7eddf55aa5bcf49efb74e88fa8d931b4d77c07eff8a6b2144472b6952
    volumes:
    - redis-data:/data
    command: [redis-server, --save, '60', '1']
    restart: always
    read_only: true
  database:
    image: postgres:17-alpine@sha256:7062a2109c4b51f3c792c7ea01e83ed12ef9a980886e3b3d380a7d2e5f6ce3f5
    volumes:
    - postgres-data:/var/lib/postgresql/data
    env_file:
    - ./environment
    restart: always
  https-portal:
    image: steveltn/https-portal:1@sha256:945b1a6fe1e2496fc8f0535a4121b2ab8e68b187b8fcdc50dacc2faf6589edd3
    volumes:
    - ssl-certs:/var/lib/https-portal
    environment:
      STAGE: production
      PROXY_READ_TIMEOUT: 3600
    ports:
    - 80:80
    - 443:443
    restart: always
  weblate:
    image: weblate/weblate@sha256:7c0f20ce0b6334cac103533696681b89e11f5970d43819c9bf7d8d10ec937e9a
    depends_on:
    - cache
    - database
    volumes:
    - weblate-data:/app/data
    - weblate-cache:/app/cache
    environment:
      WEBLATE_ENABLE_HTTPS: 1
      WEBLATE_IP_PROXY_HEADER: HTTP_X_FORWARDED_FOR
    env_file:
    - ./environment
    restart: always
    read_only: true
    tmpfs:
    - /run
    - /tmp
volumes:
  weblate-cache: {}
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
  ssl-certs: {}
