#!/bin/bash
read -rp "Also remove volumes? [yN]: " rmvol
[[ $rmvol == [yY] ]] && vol=(--volumes)

if command -v docker-compose 2>&1 /dev/null; then
    docker=(docker-compose)
else
    docker=(docker compose)
fi

"${docker[@]}" down "${vol[@]}"
