#!/bin/sh
# shellcheck disable=SC1091
. ./.test.env
echo "Checking $URL..."
TIMEOUT=0
while ! curl --insecure --fail --max-time 5 --silent --output /dev/null "$URL" ; do
    sleep 5
    TIMEOUT=$((TIMEOUT + 1))
    if [ $TIMEOUT -gt 1000 ] ; then
        break
    fi
done
curl --insecure --verbose --fail --max-time 3 "${URL}about/" | grep 'Powered by.*Weblate'
RET=$?
curl --insecure --verbose --fail --max-time 3 --output /dev/null "${URL}static/weblate-128.png"
RET2=$?
# Display logs so far
docker-compose logs

if [ $RET2 -ne 0 ] || [ $RET -ne 0 ] ; then
    exit 1
fi
