#!/bin/sh
cat > docker-compose.override.yml <<EOT
services:
  weblate:
    image: ${TEST_CONTAINER:-weblate/weblate:edge}
    restart: no
    environment:
      WEBLATE_TIME_ZONE: Europe/Prague
      WEBLATE_SITE_DOMAIN: test.example.com
      WEBLATE_SILENCED_SYSTEM_CHECKS: weblate.E003,weblate.E011,weblate.E012,weblate.E013,weblate.E017,security.W004,security.W008,security.W012,security.W018,weblate.I021,weblate.E016,weblate.I028,weblate.C030,otp_webauthn.E031
      ${TEST_EXTRA_ENV}
    ports:
      - 8080:8080
      - 4443:4443
EOT

if [ "$3" = "split" ] ; then
  mv docker-compose-split.yml docker-compose.yml
  for service in celery-backup celery-beat celery-celery celery-memory celery-notify celery-translate ; do
    cat >> docker-compose.override.yml <<EOT
  weblate-${service}:
    image: ${TEST_CONTAINER:-weblate/weblate:edge}
    restart: no
    environment:
      WEBLATE_TIME_ZONE: Europe/Prague
      WEBLATE_SITE_DOMAIN: test.example.com
EOT
  done
fi
if [ "$3" = "read-write" ] ; then
    sed -i -e '/- \/tmp/D' -e '/read_only: true/D' docker-compose.yml
else
    # Allow execution in tmp
    sed -i 's/- \/tmp/- \/tmp:exec/' docker-compose.yml
fi


IP=127.0.0.1
PORT=${1:-8080}
PROTO=${2:-http}

cat > .test.env <<EOT
URL=$PROTO://$IP:$PORT/
EOT
