#!/bin/sh
if command -v docker-compose 2>&1 /dev/null; then
    docker=(docker-compose)
else
    docker=(docker compose)
fi

$docker ps
$docker exec -T \
    --user weblate \
    weblate /app/bin/health_check
