#!/bin/bash
if command -v docker-compose 2>&1 /dev/null; then
    docker=(docker-compose)
else
    docker=(docker compose)
fi

"${docker[@]}" exec -T \
    --user weblate \
    --env WEBLATE_SILENCED_SYSTEM_CHECKS=weblate.E003,weblate.E011,weblate.E012,weblate.E013,weblate.E017,security.W004,security.W008,security.W012,security.W018,weblate.I021,weblate.E016,weblate.I028,weblate.C030 \
    weblate weblate check --deploy --fail-level WARNING
