#!/bin/sh
if command -v docker-compose 2>&1 /dev/null; then
    docker=(docker-compose)
else
    docker=(docker compose)
fi

$docker exec -T weblate pip3 list --no-cache-dir --disable-pip-version-check
