#!/bin/sh
if command -v docker-compose 2>&1 /dev/null; then
    docker=(docker-compose)
else
    docker=(docker compose)
fi

CONTAINER=$($docker ps | grep _weblate_ | sed 's/[[:space:]].*//')
docker inspect "$CONTAINER"
