{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "weblate.fullname" . }}-redis
  labels:
{{ include "weblate.labels" . | indent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: {{ .Values.redis.service.type | quote }}
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ include "weblate.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
{{- end }}
