name: Docker Compose smoke tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  smoke:
    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Read-only with SAML
          variant: saml
        - name: Read-write
          variant: read-write
        - name: Anubis
          variant: anubis
    env:
      # Use short project name, otherwise inspect output is messy
      COMPOSE_PROJECT_NAME: wl

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Generate configuration
      run: ./test-generate 8080 http "${{ matrix.variant }}"
    - name: Start containers
      run: ./test-boot
    - name: Run smoke tests
      run: ./test-smoke "${{ matrix.variant }}"
    - name: Display logs
      if: always()
      run: ./test-logs
    - name: Stop containers
      if: always()
      run: ./test-stop
